### ISSUE TITLE
Patient Detail: Treatment History

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#503]
Treatment History should show a list of all the interactions the clinical team had with the patient along with how the measures changed over time.

**Subtasks**
- [ ] API for Treatment History at a patient level within a Registry
- [ ] MUI Data grid needs to have dynamic columns based on measurements enabled

**Columns**
- Date
- Contact Type
- Weeks
- Visit Type
- Minutes
- No Show
- Measure 1
- Measure 2

**Comment by vselvarajijay** [comment]
- [ ] API for Treatment History at a patient level within a Registry
